import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import mellow from '../public/resources/mellow.mp3';
import {Switch} from 'antd';
import {UserOutlined, UsergroupAddOutlined, DownloadOutlined, LoginOutlined, BulbOutlined, BugOutlined, VerticalAlignMiddleOutlined} from '@ant-design/icons';
import SinglePlayer from '../components/SinglePlayer';
import TwoPlayer from '../components/TwoPlayer';
require('dotenv').config();

export default function Home() {

  const [api, setAPI] = useState("");

  useEffect(() => {
      if (typeof process.env.NEXT_PUBLIC_API !== "undefined") {
          setAPI(process.env.NEXT_PUBLIC_API);
      }
  }, [api])
  

  const [board, setBoard] = useState({});
  const [currentView, setCurrentView] = useState(0);
  const [playMusic, setPlayMusic] = useState(true);
  const [playSound, setPlaySound] = useState(true);
  const [controls, setControls] = useState(""); 
  const [playerStarts, setPlayerStarts] = useState(0);
  const [light, setLight] = useState(true);
  const [mode, setMode] = useState({});
  const [size, setSize] = useState(0);
  const [aiMode, setAiMode] = useState("");

  const colorConfigs = [
    {"light":
      {
        "window" : "whitesmoke",
        "win-t"  : "black",
        "win-t-s": "1px 2px lightgray",
        "modal"  : "white",
        "mdl-t"  : "lightgray",
        "mdl-t-s": "1px 2px black",
        "btn-bg" : "whitesmoke",
        "btn-b-r": "3px",
        "btn-b"  : "1px solid gray",
        "btn-t"  : "black",
        "btn-t-s": "none",
        "btn-f-w": "500",
      },
    },
    {"dark" :
      {
        "window" : "black",
        "win-t"  : "white",
        "win-t-s": "1px 1px lightgray",
        "modal"  : "linear-gradient(90deg, rgba(204,179,213,1) 0%, rgba(182,182,221,1) 100%, rgba(208,178,212,1) 100%)",
        "mdl-t"  : "gray",
        "mdl-t-s": "1px 3px black",
        "btn-bg" : "linear-gradient(90deg, rgba(204,179,213,1) 0%, rgba(182,221,215,1) 100%, rgba(208,178,212,1) 100%)",
        "btn-b-r": "5px",
        "btn-b"  : "1px solid lightgray",
        "btn-t"  : "linear-gradient(90deg, rgba(37,44,43,1) 70%, rgba(208,178,212,1) 10%, rgba(84,98,96,1) 0%)",
        "btn-t-s": "1px 1px darkgray",
        "btn-f-w": "600",
    }
  }
];

  useEffect(() => {
    if(light) {
      setMode(colorConfigs[0]['light'])
    } else {
      setMode(colorConfigs[1]['dark'])
    }
  }, [light])

  const handleChangeMode = () => {
    setLight(!light);
  }

  const apiCall = async () => {
    try{
      const res = await fetch(`${api}/get-board`, 
      {
        method: "POST",
        headers: {
          'Content-Type': 'application/json',
          'Accept': 'application/json'
        },
        body: JSON.stringify({"size": size}),
        datatpe: "json"
      })
  
      const response = await res.json()
      // console.log("KNVKNV", response['state'])
      setBoard(response['state'])
    }catch (err) {
      console.log("ERR", err)
    }
  }
    const handleChangeView = (val) => {
      setCurrentView(val);
  }

  useEffect(() => {
    apiCall()
  }, [size])
  
    const handleChangeSize = (view, val) => {
      handleChangeView(view);
      setSize(val);
  }

  useEffect(() => {
    var mellow = document && document.getElementById("mellow");
    if (playMusic) {
      mellow?.play()
    } 
    if (!playMusic) {
      mellow?.pause()
    }
    if (controls) {
      mellow.controls = true;
    } else {
      mellow.controls = false;
    }

  }, [playMusic, currentView])


  const handleShowControls = () => {
    setControls(!controls)
}

  const handlePlayMusic = () => {
    setPlayMusic(!playMusic)
}

  const handlePlaySound = () => {
    setPlaySound(!playSound)
  }

  const handlePlayerStarts = (view, val) => {
    handleChangeView(view);
    setPlayerStarts(val);
  }

  const handleChangeAI = (view, mode) => {
    handleChangeView(view)
    setAiMode(mode);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>TicTacToe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="main_container" className={styles.main_container} style={{background:`${mode['window']}`}}>
        <div style={{height:"20%", width:"100%"}}>
          <audio id="mellow" autoPlay={true} loops="true">
              <source src={mellow} type="audio/mpeg"></source>
          </audio>
          <div style={{position:"fixed", right:"35px", display:"flex", flexDirection:"column"}}>
            <button onMouseOver={() => {handleShowControls}} onMouseLeave={() => {handleShowControls}} onClick={handlePlayMusic} style={{float:"right", margin:"10px", fontSize:"1.5em", boxShadow:"1px 2px 5px lightgray", cursor:"pointer", border:"0px", padding:"0px"}}>
              {playMusic ? (<>🎵</>) : (<>🚫</>)}
            </button>
            <button onClick={handlePlaySound} style={{float:"right", margin:"10px", fontSize:"1.5em", boxShadow:"1px 2px 5px lightgray", cursor:"pointer", border:"0px", padding:"0px"}}>
              {playSound ? (<>🔊</>) : (<>🔇</>)}
            </button>
          </div>
        </div>
        {currentView == 0 && (
          <>
            <div style={{marginTop:"10px", margin:"auto", width:"300px", height:"70%", boxShadow:"1px 1px 10px lightgray", textAlign:"center", background:`${mode['modal']}`}}>
              <div style={{height:"15%"}}></div>
              <h1 style={{textShadow:`${mode['mdl-t-s']}`, color:`${mode['mdl-t']}`, fontSize:"40px", marginLeft:"25px"}}>Tic Tac Toe</h1>
              <br/>
              <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`,  fontFamily:"Roboto", fontSize:"15px", padding:"7px", width:"50%", cursor:"pointer"}} onClick={()=> {handleChangeView(1)}}>Single Player <span style={{float:"right", marginRight:"3px", fontSize:"1.1em"}}><UserOutlined/></span></button>
              <br/><br/>
              <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"15px", padding:"7px", width:"50%", cursor:"pointer"}} onClick={()=> {handleChangeView(5)}}>Two Player <span style={{float:"right", marginRight:"3px", fontSize:"1.2em"}}><UsergroupAddOutlined/></span></button>
            </div>
            <div style={{height:"10%"}}></div>
          </>
        )}

        {currentView == 1 && (
          <>
            <div style={{margin:"auto", width:"300px", height:"70%", boxShadow:"1px 1px 10px lightgray", textAlign:"center", background:`${mode['modal']}`}}>
              <div style={{height:"5%"}}></div>
              <h1 style={{textShadow:`${mode['mdl-t-s']}`, color:`${mode['mdl-t']}`, fontSize:"40px", marginLeft:"25px"}}>Tic Tac Toe</h1>
          
              <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"18px", width:"50%", cursor:"pointer"}} onClick={()=> {handleChangeSize(2, 3)}}>3 x 3</button>
              <br/><br/>
              <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`,  fontFamily:"Roboto", fontSize:"18px", width:"50%", cursor:"pointer"}} onClick={()=> {handleChangeSize(2, 4)}}>4 x 4</button>
              <br/><br/>
              <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"18px", width:"50%", cursor:"pointer"}} onClick={()=> {handleChangeSize(2, 5)}}>5 x 5</button>
              <br/><br/>
              <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"18px", width:"50%", cursor:"pointer"}} onClick={()=> {handleChangeSize(2, 6)}}>6 x 6</button>
              <br/><br/>
              <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"18px", width:"50%", cursor:"pointer"}} onClick={()=> {handleChangeSize(2, 7)}}>7 x 7</button>
            </div>
          </>
        )}
        {currentView == 2 && (
          <>
          <div style={{margin:"auto", width:"300px", height:"70%", boxShadow:"1px 1px 10px lightgray", textAlign:"center", background:`${mode['modal']}`}}>
            <div style={{height:"15%"}}></div>
            <h1 style={{textShadow:`${mode['mdl-t-s']}`, color:`${mode['mdl-t']}`, fontSize:"40px", marginLeft:"25px"}}>Tic Tac Toe</h1>
            <br/>
            <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"16px", padding:"5px", width:"55%", cursor:"pointer"}} onClick={()=> {handleChangeAI(3, "Easy")}}>Easy <span style={{float:"right", marginRight:"3px", fontSize:"1.3em"}}><BulbOutlined/></span></button>
            <br/><br/>
            <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"16px", padding:"5px", width:"55%", cursor:"pointer"}} onClick={()=> {handleChangeAI(3, "Medium")}}>Medium <span style={{float:"right", marginRight:"3px", fontSize:"1.3em"}}><VerticalAlignMiddleOutlined /></span></button>
            <br/><br/>
            <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"16px", padding:"5px", width:"55%", cursor:"pointer"}} onClick={()=> {handleChangeAI(3, "Hard")}}>Hard <span style={{float:"right", marginRight:"3px", fontSize:"1.2em"}}><BugOutlined/></span></button>
          </div>
        </>
        )}
        {currentView == 3 && (
          <>
          <div style={{margin:"auto", width:"300px", height:"70%", boxShadow:"1px 1px 10px lightgray", textAlign:"center", background:`${mode['modal']}`}}>
            <div style={{height:"15%"}}></div>
            <h1 style={{textShadow:`${mode['mdl-t-s']}`, color:`${mode['mdl-t']}`, fontSize:"40px", marginLeft:"25px"}}>Tic Tac Toe</h1>
            <br/>
            <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"16px", padding:"5px", width:"55%", cursor:"pointer"}} onClick={()=> {handlePlayerStarts(4, 1)}}>Play 1 Starts <span style={{float:"right", marginRight:"3px", fontSize:"1.3em", rotate:"270deg"}}><DownloadOutlined/></span></button>
            <br/><br/>
            <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"16px", padding:"5px", width:"55%", cursor:"pointer"}} onClick={()=> {handlePlayerStarts(4, 2)}}>Player 2 Starts <span style={{float:"right", marginRight:"3px", fontSize:"1.2em"}}><LoginOutlined/></span></button>
          </div>
        </>
        )}
        {currentView == 4 && (
          <>
            <SinglePlayer curr={board} sound={playSound} starts={playerStarts} mode={mode} aiMode={aiMode}/>
          </>
        )}

        {currentView == 5 && (
          <>
            <div style={{margin:"auto", width:"300px", height:"70%", boxShadow:"1px 1px 10px lightgray", textAlign:"center", background:`${mode['modal']}`}}>
              <div style={{height:"5%"}}></div>
              <h1 style={{textShadow:`${mode['mdl-t-s']}`, color:`${mode['mdl-t']}`, fontSize:"40px", marginLeft:"25px"}}>Tic Tac Toe</h1>
          
              <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"18px", width:"50%", cursor:"pointer"}} onClick={()=> {handleChangeSize(6, 3)}}>3 x 3</button>
              <br/><br/>
              <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`,  fontFamily:"Roboto", fontSize:"18px", width:"50%", cursor:"pointer"}} onClick={()=> {handleChangeSize(6, 4)}}>4 x 4</button>
              <br/><br/>
              <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"18px", width:"50%", cursor:"pointer"}} onClick={()=> {handleChangeSize(6, 5)}}>5 x 5</button>
              <br/><br/>
              <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"18px", width:"50%", cursor:"pointer"}} onClick={()=> {handleChangeSize(6, 6)}}>6 x 6</button>
              <br/><br/>
              <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"18px", width:"50%", cursor:"pointer"}} onClick={()=> {handleChangeSize(6, 7)}}>7 x 7</button>
            </div>
          </>
        )}

        {currentView == 6 && (
          <>
            <div style={{margin:"auto", width:"300px", height:"70%", boxShadow:"1px 1px 10px lightgray", textAlign:"center", background:`${mode['modal']}`}}>
              <div style={{height:"15%"}}></div>
              <h1 style={{textShadow:`${mode['mdl-t-s']}`, color:`${mode['mdl-t']}`, fontSize:"40px", marginLeft:"25px"}}>Tic Tac Toe</h1>
              <br/>
              <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"16px", padding:"5px", width:"55%", cursor:"pointer"}} onClick={()=> {handlePlayerStarts(7, 1)}}>Play 1 Starts <span style={{float:"right", marginRight:"3px", fontSize:"1.3em", rotate:"270deg"}}><DownloadOutlined/></span></button>
              <br/><br/>
              <button style={{background:`${mode['btn-bg']}`, fontWeight:`${mode['btn-f-w']}`, border:`${mode['btn-b']}`, borderRadius:`${mode['btn-b-r']}`, color:`${mode['btn-t']}`, textShadow:`${mode['btn-t-s']}`, fontFamily:"Roboto", fontSize:"16px", padding:"5px", width:"55%", cursor:"pointer"}} onClick={()=> {handlePlayerStarts(7, 2)}}>Player 2 Starts <span style={{float:"right", marginRight:"3px", fontSize:"1.2em"}}><LoginOutlined/></span></button>
            </div>
          </>
        )}

        {currentView == 7 && (
          <>
            <TwoPlayer curr={board} sound={playSound} starts={playerStarts} mode={mode}/>
          </>
        )}


      </div>

      {/* <h1>Hi {JSON.stringify(board)}</h1> */}


      {/* <button onClick={apiCall}>Play</button> */}

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          style={{all:"initial"}}
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      <div style={{display:"flex", justifyContent:"center"}}>
        <p style={{all:"unset", marginRight:"7px"}}>🔆</p><Switch defaultChecked={false} onChange={handleChangeMode}/><p style={{all:"unset", marginLeft:"7px"}}>🌑</p>
      </div>
    </div>
  )
}
